version: '3.8'

services:
  brain_postgres:
    image: postgres:15
    container_name: brain_postgres
    restart: always
    environment:
      POSTGRES_DB: brain_agriculture_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
